import { Component, getComponentTree } from "./meta-data";
import { StringBuilder } from "./string-builder";

export function addHeader(sb: StringBuilder, components: Component[]) {
    sb.writeln("// This file is auto-generated by vscode-dynamic-theme");
    sb.writeln("// Do not edit this file directly");
    sb.writeln();
    sb.writeln(`// Page Routes`);
    for (const c of components) {
        const tree = getComponentTree(c, components);
        sb.writeln(`// "${c.route}": ${tree.map(x => x.name).join(" > ")}`);
    }
    sb.writeln();
}